stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  cache:
    paths:
      - target/
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check
    - cargo build --verbose
    - cargo test --verbose
