stages:
  - check-format
  - build
  - package

variables:
  GIT_SUBMODULE_STRATEGY: recursive

merge-requests:
  stage: check-format
  only:
    - merge_requests
  image: rust:latest
  script:
    - rustup component add rustfmt
    - cargo fmt --all -- --check

rust-latest:
  stage: build
  only:
    refs:
      - master
  image: rust:latest
  except:
    - tags
  cache:
    paths:
      - target/
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq --no-install-recommends clang cmake libhyperscan-dev
  script:
    - cargo build --verbose
    - cargo test --all --verbose

release:
  only: ['tags']
  stage: package
  image: docker:stable
  services:
    - docker:dind
  script:
    - export DOCKER_HOST=tcp://docker:2375/
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
