[package]
name = "review"
version = "0.2.0"
authors = [
    "Atsushi Yoshioka <yoshioka@petabi.com>",
    "Min Kim <msk@petabi.com>",
]
edition = "2018"
publish = false

[dependencies]
chrono = "0.4.0"
clap = "2"
cursive = "0.10"
serde = "1.0.84"
serde_derive = "1.0.84"
serde_json = "1.0.35"
