[package]
name = "review"
version = "0.3.0"
authors = [
    "Atsushi Yoshioka <yoshioka@petabi.com>",
    "Min Kim <msk@petabi.com>",
]
edition = "2018"
publish = false

[dependencies]
chrono = "0.4"
clap = "2"
cursive = "0.10"
serde = { version = "1",  features = ["derive"] }
serde_json = "1"
