[package]
name = "review"
version = "0.3.6"
authors = [
    "Atsushi Yoshioka <yoshioka@petabi.com>",
    "Min Kim <msk@petabi.com>",
]
edition = "2018"
publish = false

[dependencies]
api_service = { path = "./api_service" }
clap = "2"
dotenv = "0.13"
futures = "0.1"
hyper = "0.12"
client = { path = "./client" }
serde = { version = "1",  features = ["derive"] }
serde_json = "1"
url = "1.7"
