[package]
name = "review"
version = "0.2.0"
authors = [
    "Atsushi Yoshioka <yoshioka@petabi.com>",
    "Min Kim <msk@petabi.com>",
]
publish = false

[dependencies]
clap = "2"
cursive = "0.9"
sqlite = "0.24.0"
quale = "1.0.0"
