DROP FUNCTION IF EXISTS insert_data_source(VARCHAR, VARCHAR);
DROP FUNCTION IF EXISTS attempt_cluster_upsert(NUMERIC, VARCHAR, VARCHAR, VARCHAR, INTEGER, NUMERIC[], VARCHAR, FLOAT8, NUMERIC);
DROP FUNCTION IF EXISTS attempt_outlier_upsert(NUMERIC, INTEGER, BYTEA, VARCHAR, VARCHAR, NUMERIC[], NUMERIC);
