DROP TRIGGER after_data_source_insertion_trigger on data_source;
DROP FUNCTION insert_empty_raw_event();

DROP TABLE top_n_datetime;
DROP TABLE top_n_ipaddr;
DROP TABLE top_n_text;
DROP TABLE top_n_float;
DROP TABLE top_n_enum;
DROP TABLE top_n_int;
DROP TABLE description_datetime;
DROP TABLE description_ipaddr;
DROP TABLE description_text;
DROP TABLE description_float;
DROP TABLE description_enum;
DROP TABLE description_int;
DROP TABLE column_description;
DROP TABLE description_element_type;
DROP TABLE token;
DROP TABLE indicator;
DROP TABLE outlier;
DROP TABLE cluster;
DROP TABLE status;
DROP TABLE qualifier;
DROP TABLE raw_event;
DROP TABLE data_source;
DROP TABLE category;
