name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        rust: [stable, 1.39.0]

    steps:
    - name: Install Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Install libraries
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install libpq-dev
    - uses: actions/checkout@master
    - name: Build
      run: cargo build --verbose
    - name: Install components
      if: matrix.os == 'ubuntu-latest' && matrix.rust == 'stable'
      run: rustup component add clippy rustfmt
    - name: Check formatting
      if: matrix.os == 'ubuntu-latest' && matrix.rust == 'stable'
      run: cargo fmt -- --check
    - name: Clippy
      if: matrix.os == 'ubuntu-latest' && matrix.rust == 'stable'
      run: cargo clippy -- -D warnings
