name: Release

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Authenticate to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u petabi --password-stdin
    - name: Build Docker image
      run: docker build -t docker.pkg.github.com/petabi/review/review:${GITHUB_REF:10} .
    - name: Upload Docker image
      run: docker push docker.pkg.github.com/petabi/review/review:${GITHUB_REF:10}
